name: example
description: this is example of public internal lint

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  meta: any
  public_internal_annotation:
    path: ../../public_internal_annotation

dev_dependencies:
  public_internal:
    path: ../