name: example
description: this is example of public internal lint

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: any
  public_internal_annotation:
    path: ../../public_internal_annotation

dev_dependencies:
  lints: ^2.0.0
  custom_lint:
  public_internal:
    path: ../