name: public_internal
description: Linter to make class only accessible within its directory or subdirectories.
version: 1.0.0
homepage: https://github.com/aarajput/dart_public_internal/tree/master/packages/public_internal
repository: https://github.com/aarajput/dart_public_internal
issue_tracker: https://github.com/aarajput/dart_public_internal/issues
documentation: https://github.com/aarajput/dart_public_internal/blob/master/packages/public_internal/README.md

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  custom_lint_builder: ^0.0.9+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
